let catalog, products=[], filtered=[], visible=18;
const state={brand:'All',category:'All',era:'All',collection:'All',query:''};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const image=(p,c='')=>`<img class="product-image ${c}" src="${esc(p.image)}" alt="${esc(p.title)} patent artwork" loading="lazy">`;
function options(el,values,current){el.innerHTML=['All',...values].map(v=>`<option ${v===current?'selected':''}>${esc(v)}</option>`).join('')}
function filter(reset=true){const q=state.query.toLowerCase();filtered=products.filter(p=>(state.brand==='All'||p.brand===state.brand)&&(state.category==='All'||p.category===state.category)&&(state.era==='All'||p.era===state.era)&&(state.collection==='All'||p.collections.includes(state.collection))&&(!q||[p.title,p.brand,p.patent,p.patentTitle,p.category,...p.technologies,...p.collections].join(' ').toLowerCase().includes(q)));if(reset)visible=18;renderArchive()}
function toolbar(){[['brandFilter','brand',catalog.brands],['categoryFilter','category',catalog.categories],['eraFilter','era',catalog.eras],['collectionFilter','collection',catalog.collections]].forEach(([id,key,list])=>{const el=$('#'+id);options(el,list.map(x=>x.name),state[key]);el.onchange=e=>{state[key]=e.target.value;filter()}});$('#archiveSearch').oninput=e=>{state.query=e.target.value;filter()};$('#clearFilters').onclick=()=>{Object.assign(state,{brand:'All',category:'All',era:'All',collection:'All',query:''});$('#archiveSearch').value='';toolbar();filter()}}
function card(p){return `<article class="archive-card" data-product="${p.id}" tabindex="0"><div class="card-art"><span class="catalog-index">${p.archiveId}</span>${image(p)}</div><div class="card-meta"><span>${esc(p.brand)}</span><span>${esc(p.year)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.patent)} · ${esc(p.category)}</p><button class="story-link">Read the object story →</button></article>`}
function renderArchive(){const shown=filtered.slice(0,visible);$('#archiveGrid').innerHTML=shown.length?shown.map(card).join(''):'<div class="empty-state">No finished works match these filters.</div>';$('#archiveCount').textContent=`${shown.length} of ${filtered.length} works`;$('#viewAll').hidden=visible>=filtered.length;wire($('#archiveGrid'))}
function renderBrands(){$('#brandCount').textContent=`${catalog.brands.length} makers · ${products.length} finished works`;$('#brandList').innerHTML=catalog.brands.map((b,i)=>`<a href="#archive" data-brand="${esc(b.name)}"><span>${String(i+1).padStart(2,'0')}</span>${esc(b.name)}<small>${b.count}</small><b>→</b></a>`).join('');$$('[data-brand]').forEach(a=>a.onclick=()=>{state.brand=a.dataset.brand;$('#brandFilter').value=state.brand;filter()})}
function renderCollections(){const list=catalog.collections.filter(x=>x.count>=3).slice(0,12);$('#collectionGrid').innerHTML=list.map((c,i)=>{const samples=products.filter(p=>p.collections.includes(c.name)).slice(0,3);return `<article class="collection-card" data-collection="${esc(c.name)}" tabindex="0"><div class="collection-preview">${samples.map(image).join('')}</div><span class="collection-number">COLLECTION ${String(i+1).padStart(2,'0')}</span><h3>${esc(c.name)}</h3><p>${c.count} finished works linked by maker, era, technology, or design language.</p><div class="collection-foot"><span>${c.count} works</span><button>Explore →</button></div></article>`}).join('');$$('[data-collection]').forEach(c=>c.onclick=()=>{state.collection=c.dataset.collection;$('#collectionFilter').value=state.collection;filter();location.hash='archive'})}
function renderPairings(){const ids=['wpa-0137','wpa-0099','wpa-0115'],watches=['Rolex Submariner','Omega Specialities CK 859','Patek Philippe Alarm Travel Time'];$('#pairingGrid').innerHTML=ids.map((id,i)=>{const p=products.find(x=>x.id===id)||products[i];return `<article class="pair-card" data-product="${p.id}" tabindex="0"><div class="pair-visual"><div class="watch-silhouette"><span></span></div><div class="mini-print">${image(p)}</div><span class="plus">+</span></div><span class="eyebrow">PAIRING ${String(i+1).padStart(2,'0')}</span><h3>${watches[i]}</h3><strong>${esc(p.title)}</strong><p>A direct connection between a collector's watch and the protected design language behind it.</p><button class="story-link">View pairing →</button></article>`}).join('');wire($('#pairingGrid'))}
function related(p){return products.filter(x=>x.id!==p.id).map(x=>({x,s:(x.brand===p.brand?6:0)+(x.category===p.category?4:0)+(x.era===p.era?2:0)+x.collections.filter(v=>p.collections.includes(v)).length*5})).filter(r=>r.s).sort((a,b)=>b.s-a.s).slice(0,4).map(r=>r.x)}
function openDetail(id,hash=true){
  const p=products.find(x=>x.id===id);if(!p)return;
  $('#detailModal').innerHTML=`<button class="modal-close" data-close>×</button>
    <div class="detail-art"><div class="detail-paper">${image(p,'detail-image')}</div></div>
    <div class="detail-copy">
      <span class="eyebrow">${p.archiveId} / Ready for sale</span>
      <h2>${esc(p.title)}</h2>
      <p class="detail-deck">${esc(p.patentTitle)} · ${esc(p.patent)}</p>
      <div class="object-register"><div><span>Maker</span><strong>${esc(p.brand)}</strong></div><div><span>Era</span><strong>${esc(p.era)}</strong></div><div><span>Category</span><strong>${esc(p.category)}</strong></div></div>
      <p class="listing-intro">${esc(p.editorialSummary)}</p>
      <div class="listing-essentials"><span>Listing details</span><ul>${p.essentials.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></div>
      <h3>Reading the drawing</h3><p>${esc(p.designReading)}</p>
      <h3>The collector angle</h3><p>${esc(p.collectorAngle)}</p>
      <h3>On the wall</h3><p>${esc(p.wallStory)}</p>
      <div class="detail-tags">${[p.category,p.era,...p.technologies,...p.collections].map(x=>`<span>${esc(x)}</span>`).join('')}</div>
      <div class="buy-box"><div><span>Available print sizes</span><strong>${esc(p.sizes.join(' · '))}</strong><small>Finished artwork · printed to order</small></div><button class="primary-button" data-interest>Choose this work</button></div>
      <div class="related-block"><span class="eyebrow">Related works</span><div>${related(p).map(x=>`<button data-product="${x.id}">${image(x)}<span>${esc(x.title)}</span></button>`).join('')}</div></div>
    </div>`;
  $('#detailBackdrop').hidden=false;document.body.classList.add('modal-open');$('[data-close]').onclick=closeDetail;$('[data-interest]').onclick=e=>e.currentTarget.textContent='Selected for inquiry ✓';wire($('.related-block'));if(hash)history.replaceState(null,'',`#product=${p.id}`)
}
function closeDetail(){$('#detailBackdrop').hidden=true;document.body.classList.remove('modal-open');if(location.hash.startsWith('#product='))history.replaceState(null,'','#archive')}
function wire(root){$$('[data-product]',root).forEach(el=>{el.onclick=e=>{e.stopPropagation();openDetail(el.dataset.product)};el.onkeydown=e=>{if(e.key==='Enter')openDetail(el.dataset.product)}})}
function matcherMarkup(id){return `<div class="matcher-card" data-matcher="${id}"><div class="matcher-intro"><span class="eyebrow">The Collection Builder</span><h2>Tell us what is in your watch box.</h2><p>We’ll find finished works connected by maker, model, era, and design language.</p></div><div class="watch-entry"><div class="watch-input"><input placeholder="Add watches, brands or references…"><button data-build>Build my patent set</button></div></div><div class="matcher-results" hidden></div></div>`}
function setupMatcher(container){const root=$('[data-matcher]',container),input=$('input',root),results=$('.matcher-results',root);$('[data-build]',root).onclick=()=>{const terms=input.value.toLowerCase().split(/\s+/).filter(x=>x.length>2);const picks=products.map(p=>({p,s:terms.filter(t=>[p.brand,p.title,p.patent,...p.collections].join(' ').toLowerCase().includes(t)).length})).sort((a,b)=>b.s-a.s).slice(0,6).map(x=>x.p);results.innerHTML=`<span class="eyebrow">Your archive edit</span><div>${picks.map(p=>`<button class="result-row" data-product="${p.id}">${image(p)}<div><strong>${esc(p.title)}</strong><small>${esc(p.brand)} · ${esc(p.category)}</small></div></button>`).join('')}</div>`;results.hidden=false;wire(results)}}
async function init(){catalog=await(await fetch('./catalog.json?v=20260816-2')).json();products=catalog.products.filter(p=>p.status==='Ready for Sale');filtered=[...products];toolbar();renderArchive();renderBrands();renderCollections();renderPairings();wire($('.story-feature'));$('#viewAll').onclick=()=>{visible+=18;renderArchive()};$('#matcherInline').innerHTML=matcherMarkup('inline');setupMatcher($('#matcherInline'));$('#matcherModal').innerHTML=matcherMarkup('modal');setupMatcher($('#matcherModal'));$$('[data-open-matcher]').forEach(b=>b.onclick=()=>{$('#matcherBackdrop').hidden=false;document.body.classList.add('modal-open')});$$('[data-close-matcher]').forEach(b=>b.onclick=()=>{$('#matcherBackdrop').hidden=true;document.body.classList.remove('modal-open')});$('#detailBackdrop').onmousedown=e=>{if(e.target===e.currentTarget)closeDetail()};$('#menuOpen').onclick=()=>$('#mobileMenu').hidden=false;$('#menuClose').onclick=()=>$('#mobileMenu').hidden=true;$('#wallSubmit').onclick=e=>e.currentTarget.textContent='Submissions opening soon';$('#newsletterForm').onsubmit=e=>{e.preventDefault();$('button',e.currentTarget).textContent='Added ✓'};document.onkeydown=e=>{if(e.key==='Escape')closeDetail()};const id=location.hash.match(/^#product=(wpa-\d+)$/i)?.[1];if(id)openDetail(id.toLowerCase(),false)}
document.addEventListener('DOMContentLoaded',()=>init().catch(e=>{console.error(e);$('#archiveGrid').innerHTML='<div class="empty-state">The archive could not be loaded.</div>'}));
