const brands = ['All','Rolex','Omega','Patek Philippe','Audemars Piguet','Cartier','Breitling','TAG Heuer','Bulova','Seiko','Citizen','Timex','Swatch','Waltham','Elgin','Illinois Watch','Richard Mille'];

const archive = [
  { id:'diver-bezel',brand:'Rolex',title:'The Rotating Bezel',kicker:'Tool watch language',era:'Mid-century',theme:'Diving',patent:'Verified patent record to be imported',story:'A small mechanical interface became one of the clearest visual signatures in modern watchmaking. This exhibition treatment focuses on the way a functional timing device became part of the cultural vocabulary of the dive watch.',why:'For a collection, the drawing works because it is immediately legible from across a room: case, bezel, crown and timing geometry read as a watch before the viewer ever notices the technical callouts.',collection:'The Diver’s Toolkit',drawing:'bezel' },
  { id:'moon-chrono',brand:'Omega',title:'Chronograph Architecture',kicker:'Timing under pressure',era:'Space age',theme:'Chronograph',patent:'Verified patent record to be imported',story:'The chronograph is one of watchmaking’s best examples of complexity becoming intuitive. Push, stop, read, reset: an entire mechanical conversation translated into a few gestures on the wrist.',why:'The layered registers and case geometry make chronograph patent drawings unusually strong wall pieces. They reward both a quick glance and a closer look.',collection:'Timing the Impossible',drawing:'chrono' },
  { id:'nautilus-form',brand:'Patek Philippe',title:'Case as Architecture',kicker:'The luxury sports watch',era:'1970s',theme:'Case design',patent:'Verified patent record to be imported',story:'The most influential luxury sports watches changed the role of the case. It was no longer a container around the movement; it became the identity of the object itself.',why:'Strong silhouette, restrained geometry and an instantly architectural profile make this the kind of drawing that can anchor an entire wall.',collection:'Integrated Icons',drawing:'case' },
  { id:'royal-oak-form',brand:'Audemars Piguet',title:'The Exposed Structure',kicker:'Industrial form, elevated',era:'1970s',theme:'Case design',patent:'Verified patent record to be imported',story:'Luxury watchmaking has often hidden the means of assembly. The integrated sports-watch era did the opposite: screws, edges and junctions became the visual language.',why:'This is a print for collectors who like objects that explain themselves. The engineering is part of the ornament.',collection:'Integrated Icons',drawing:'octagon' },
  { id:'santos-geometry',brand:'Cartier',title:'Geometry on the Wrist',kicker:'A watch becomes design',era:'Early modern',theme:'Case design',patent:'Verified patent record to be imported',story:'Cartier’s great contribution to watch culture is not only mechanical. It is the insistence that a wristwatch can be read as pure design: proportion, line, hardware and negative space.',why:'Paired with technical patents, a geometric case drawing changes the rhythm of a wall and makes a collection feel deliberately composed.',collection:'Shape of Time',drawing:'square' },
  { id:'accutron',brand:'Bulova',title:'Electronic Timekeeping',kicker:'The tuning-fork age',era:'1960s',theme:'Electronic',patent:'Verified patent record to be imported',story:'The electronic watch arrived before quartz made electronics ordinary. The Accutron era belongs to the thrilling middle chapter when a watch could still feel visibly mechanical and unmistakably futuristic at the same time.',why:'For the wall, the story is unusually easy to tell: this is the moment a centuries-old machine learned a new language.',collection:'Electric Time',drawing:'electric' },
  { id:'seiko-quartz',brand:'Seiko',title:'Precision at Scale',kicker:'Quartz changes the world',era:'Quartz era',theme:'Electronic',patent:'Verified patent record to be imported',story:'Quartz was more than a new movement. It changed what accuracy cost, who could own it and how the entire industry thought about the meaning of mechanical craft.',why:'Technical electronic drawings add contrast to a collection of cases and dials while telling one of the largest technological shifts in watch history.',collection:'Electric Time',drawing:'circuit' },
  { id:'breitling-chrono',brand:'Breitling',title:'Information at a Glance',kicker:'Instrument thinking',era:'Aviation age',theme:'Chronograph',patent:'Verified patent record to be imported',story:'Instrument watches are designed around a promise: complicated information must become useful in seconds. Breitling’s visual history makes that promise unusually literal.',why:'Dense markings and purposeful geometry give this kind of patent art a cockpit-instrument character without needing color.',collection:'Timing the Impossible',drawing:'dial' }
];

const curated = [
  { title:'Electric Time',subtitle:'When watchmaking learned a new language',count:6,tags:['Bulova','Seiko','Citizen'],symbol:'ϟ' },
  { title:'Integrated Icons',subtitle:'The case becomes the identity',count:5,tags:['Audemars Piguet','Patek Philippe'],symbol:'◇' },
  { title:'Timing the Impossible',subtitle:'Chronographs, instruments and split seconds',count:8,tags:['Omega','Breitling','TAG Heuer'],symbol:'◴' },
  { title:'Shape of Time',subtitle:'The wristwatch as industrial design',count:7,tags:['Cartier','Richard Mille','Swatch'],symbol:'□' }
];

const pairings = [
  { watch:'Vintage dive watch',art:'Rotating Bezel Study',note:'A functional pairing with immediate visual recognition.',drawing:'bezel' },
  { watch:'1960s electronic watch',art:'Electric Time Diptych',note:'A giftable story about the moment electricity entered the wristwatch.',drawing:'electric' },
  { watch:'Integrated-bracelet sports watch',art:'Case Architecture No. 01',note:'Turn the silhouette you wear into the architecture on your wall.',drawing:'case' }
];

let activeBrand = 'All';
const esc = value => String(value).replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));

function drawing(kind='bezel', compact=false){
  const line = d => `<path d="${d}" fill="none" stroke="currentColor" stroke-width="1.35" vector-effect="non-scaling-stroke"/>`;
  const circle=(cx,cy,r)=>`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="currentColor" stroke-width="1.35" vector-effect="non-scaling-stroke"/>`;
  const rect=(x,y,w,h,rx=0)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="none" stroke="currentColor" stroke-width="1.35" vector-effect="non-scaling-stroke"/>`;
  let body='';
  if(kind==='bezel') body = circle(160,150,88)+circle(160,150,68)+line('M160 56v16M160 228v16M66 150h16M238 150h16M94 84l12 12M214 204l12 12M226 84l-12 12M106 204l-12 12')+rect(245,132,28,36,5)+line('M160 99v55l40 23');
  else if(kind==='chrono') body = circle(160,150,92)+circle(125,162,28)+circle(195,162,28)+circle(160,108,22)+line('M252 118h23M252 148h30M252 178h23M160 76v74l34 18');
  else if(kind==='case') body = line('M90 78h140l24 28v88l-24 28H90l-24-28v-88z')+rect(103,95,114,110,48)+line('M118 55h84v23M118 222v26h84v-26M254 138h31v24h-31');
  else if(kind==='octagon') { body=line('M110 68h100l50 50v64l-50 50H110l-50-50v-64z')+circle(160,150,65); [0,45,90,135,180,225,270,315].forEach(a=>{const r=88,x=160+Math.cos(a*Math.PI/180)*r,y=150+Math.sin(a*Math.PI/180)*r;body+=circle(x,y,3.5)}); }
  else if(kind==='square') { body=rect(78,68,164,164,24)+rect(98,88,124,124,10)+line('M115 46h90v22M115 232v24h90v-24M242 137h30v26h-30'); [0,1,2,3,4,5,6,7].forEach(i=>body+=circle(i<4?96+i*43:96+(i-4)*43,i<4?78:222,3)); }
  else if(kind==='electric') body = circle(152,148,72)+line('M102 148h28l11-28 20 58 17-45 12 15h34')+line('M226 116c28 12 28 52 0 64M84 111c-31 18-31 59 0 77')+circle(152,148,14);
  else if(kind==='circuit') body = rect(78,76,164,148,8)+rect(130,120,60,56)+line('M78 104h34v32h18M78 190h38v-28h14M190 136h26v-30h26M190 162h30v34h22M144 120V92h-26M176 176v26h-24')+circle(112,104,5)+circle(220,196,5);
  else if(kind==='dial') { body=circle(160,150,92)+circle(160,150,54)+line('M160 78v72l38 24'); Array.from({length:12}).forEach((_,i)=>{const a=i*30*Math.PI/180; body+=line(`M${160+Math.sin(a)*76} ${150-Math.cos(a)*76} L${160+Math.sin(a)*86} ${150-Math.cos(a)*86}`)}); }
  const labels = compact ? '' : '<text x="20" y="28">FIG. 1</text><text x="280" y="288">ARCHIVE STUDY</text>';
  const foot = compact ? '' : `${line('M18 250h86M216 250h86M18 258h52M250 258h52')}<text x="20" y="276">PATENT ARCHIVE</text>`;
  return `<svg class="patent-drawing" viewBox="0 0 320 300" aria-hidden="true">${labels}${body}${foot}</svg>`;
}

function hydrateDrawings(root=document){ root.querySelectorAll('[data-drawing]').forEach(el => el.innerHTML=drawing(el.dataset.drawing, el.closest('.frame')!==null)); }
function renderFilters(){ const el=document.getElementById('archiveFilters'); el.innerHTML=brands.slice(0,9).map(b=>`<button class="filter ${activeBrand===b?'active':''}" data-brand="${esc(b)}">${esc(b)}</button>`).join(''); el.querySelectorAll('[data-brand]').forEach(btn=>btn.addEventListener('click',()=>{activeBrand=btn.dataset.brand;renderFilters();renderArchive();})); }
function renderArchive(){ const el=document.getElementById('archiveGrid'); const items=activeBrand==='All'?archive:archive.filter(i=>i.brand===activeBrand); if(!items.length){ el.innerHTML='<div class="empty-state">This brand is ready for your verified patent catalog. The archive structure is already in place.</div>'; return; } el.innerHTML=items.slice(0,6).map((item,index)=>`<article class="archive-card" data-open-story="${item.id}" tabindex="0"><div class="card-art"><span class="catalog-index">${String(index+1).padStart(2,'0')}</span>${drawing(item.drawing,true)}</div><div class="card-meta"><span>${esc(item.brand)}</span><span>${esc(item.era)}</span></div><h3>${esc(item.title)}</h3><p>${esc(item.kicker)}</p><button class="story-link">Read the story →</button></article>`).join(''); wireStoryTriggers(el); }
function renderBrands(){ document.getElementById('brandList').innerHTML=brands.slice(1).map((b,i)=>`<a href="#archive" data-brand-link="${esc(b)}"><span>${String(i+1).padStart(2,'0')}</span>${esc(b)}<b>→</b></a>`).join(''); document.querySelectorAll('[data-brand-link]').forEach(a=>a.addEventListener('click',()=>{activeBrand=a.dataset.brandLink;renderFilters();renderArchive();})); }
function renderCollections(){ document.getElementById('collectionGrid').innerHTML=curated.map((c,i)=>`<article class="collection-card"><div class="collection-symbol">${c.symbol}</div><span class="collection-number">COLLECTION ${String(i+1).padStart(2,'0')}</span><h3>${esc(c.title)}</h3><p>${esc(c.subtitle)}</p><div class="tag-row">${c.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="collection-foot"><span>${c.count} works</span><button>Explore →</button></div></article>`).join(''); }
function renderPairings(){ document.getElementById('pairingGrid').innerHTML=pairings.map((p,i)=>`<article class="pair-card"><div class="pair-visual"><div class="watch-silhouette"><span></span></div><div class="mini-print">${drawing(p.drawing,true)}</div><span class="plus">+</span></div><span class="eyebrow">PAIRING ${String(i+1).padStart(2,'0')}</span><h3>${esc(p.watch)}</h3><strong>${esc(p.art)}</strong><p>${esc(p.note)}</p><button class="story-link" data-open-story="${archive[i].id}">View pairing →</button></article>`).join(''); wireStoryTriggers(document.getElementById('pairingGrid')); }

function openDetail(id){ const item=archive.find(i=>i.id===id); if(!item)return; const modal=document.getElementById('detailModal'); modal.innerHTML=`<button class="modal-close" data-close-detail>×</button><div class="detail-art"><div class="detail-paper"><div class="sheet-meta"><span>${esc(item.brand.toUpperCase())}</span><span>${esc(item.era.toUpperCase())}</span></div>${drawing(item.drawing,false)}</div></div><div class="detail-copy"><span class="eyebrow">Object story / ${esc(item.collection)}</span><h2>${esc(item.title)}</h2><p class="detail-deck">${esc(item.kicker)}</p><div class="object-register"><div><span>Maker</span><strong>${esc(item.brand)}</strong></div><div><span>Era</span><strong>${esc(item.era)}</strong></div><div><span>Archive record</span><strong>${esc(item.patent)}</strong></div></div><h3>Why this matters</h3><p>${esc(item.story)}</p><h3>Why it belongs on the wall</h3><p>${esc(item.why)}</p><div class="buy-box"><div><span>Archival print</span><strong>From $48</strong><small>Prototype pricing · unframed · multiple sizes</small></div><button class="primary-button">▱ Choose size</button></div></div>`; document.getElementById('detailBackdrop').hidden=false;document.body.classList.add('modal-open'); modal.querySelector('[data-close-detail]').addEventListener('click',closeDetail); }
function closeDetail(){document.getElementById('detailBackdrop').hidden=true;document.body.classList.remove('modal-open');}
function wireStoryTriggers(root=document){root.querySelectorAll('[data-open-story]').forEach(el=>{el.addEventListener('click',()=>openDetail(el.dataset.openStory));el.addEventListener('keydown',e=>{if(e.key==='Enter')openDetail(el.dataset.openStory)});});}

function matcherMarkup(prefix){ return `<div class="matcher-card" data-matcher="${prefix}"><div class="matcher-intro"><span class="eyebrow">The Collection Builder</span><h2>Tell us what is in your watch box.</h2><p>We’ll build a wall around the watches, eras and design language you already care about.</p></div><div class="watch-entry"><div class="watch-chips"></div><div class="watch-input"><input placeholder="Add a watch, brand or reference…"><button data-add-watch>Add</button></div><div class="style-question"><span>What should the room say?</span><div><button>Technical</button><button>Historic</button><button>Minimal</button><button>Unexpected</button></div></div><button class="primary-button full" data-build-set>✦ Build my patent set</button></div><div class="matcher-results" hidden></div></div>`; }
function setupMatcher(container){ const root=container.querySelector('[data-matcher]'); if(!root)return; let watches=['Rolex Submariner','Cartier Santos']; const chips=root.querySelector('.watch-chips'), input=root.querySelector('input'), results=root.querySelector('.matcher-results'); function renderChips(){chips.innerHTML=watches.map((w,i)=>`<span>${esc(w)}<button data-remove-watch="${i}">×</button></span>`).join('');chips.querySelectorAll('[data-remove-watch]').forEach(b=>b.addEventListener('click',()=>{watches.splice(Number(b.dataset.removeWatch),1);renderChips();results.hidden=true;}));} function add(){const value=input.value.trim();if(!value)return;watches.push(value);input.value='';renderChips();results.hidden=true;} root.querySelector('[data-add-watch]').addEventListener('click',add);input.addEventListener('keydown',e=>{if(e.key==='Enter')add();}); root.querySelector('[data-build-set]').addEventListener('click',()=>{const text=watches.join(' ').toLowerCase();let picks=[];if(/rolex|submariner|diver|seamaster/.test(text))picks.push(archive[0]);if(/cartier|santos|tank|square/.test(text))picks.push(archive[4]);if(/omega|speedmaster|chrono|breitling|heuer/.test(text))picks.push(archive[1]);if(/bulova|accutron|seiko|citizen|quartz/.test(text))picks.push(archive[5]);if(/patek|nautilus|audemars|royal oak|integrated/.test(text))picks.push(archive[2]);archive.forEach(item=>{if(picks.length<3&&!picks.includes(item))picks.push(item)});picks=picks.slice(0,3);results.innerHTML=`<span class="eyebrow">Your first edit</span><div>${picks.map((item,i)=>`<div class="result-row"><span>${i+1}</span>${drawing(item.drawing,true)}<div><strong>${esc(item.title)}</strong><small>${esc(item.brand)} · ${esc(item.collection)}</small></div></div>`).join('')}</div><p>This is the beginning of the experience: the production version can score your exact references, room style, preferred eras and existing art.</p>`;results.hidden=false;}); renderChips(); }
function openMatcher(){document.getElementById('matcherBackdrop').hidden=false;document.body.classList.add('modal-open');}
function closeMatcher(){document.getElementById('matcherBackdrop').hidden=true;document.body.classList.remove('modal-open');}

function init(){ hydrateDrawings();renderFilters();renderArchive();renderBrands();renderCollections();renderPairings();wireStoryTriggers(document.querySelector('.story-feature')); document.getElementById('matcherInline').innerHTML=matcherMarkup('inline');setupMatcher(document.getElementById('matcherInline')); document.getElementById('matcherModal').innerHTML=matcherMarkup('modal');setupMatcher(document.getElementById('matcherModal')); document.querySelectorAll('[data-open-matcher]').forEach(b=>b.addEventListener('click',openMatcher));document.querySelectorAll('[data-close-matcher]').forEach(b=>b.addEventListener('click',closeMatcher)); document.getElementById('detailBackdrop').addEventListener('mousedown',e=>{if(e.target===e.currentTarget)closeDetail();});document.getElementById('matcherBackdrop').addEventListener('mousedown',e=>{if(e.target===e.currentTarget)closeMatcher();}); document.getElementById('viewAll').addEventListener('click',()=>{activeBrand='All';renderFilters();renderArchive();}); document.getElementById('menuOpen').addEventListener('click',()=>document.getElementById('mobileMenu').hidden=false);document.getElementById('menuClose').addEventListener('click',()=>document.getElementById('mobileMenu').hidden=true);document.querySelectorAll('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>document.getElementById('mobileMenu').hidden=true)); document.getElementById('wallSubmit').addEventListener('click',e=>e.currentTarget.textContent='✓ Submission noted for prototype');document.getElementById('newsletterForm').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('button').textContent='Added to the reading list ✓';}); document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDetail();closeMatcher();document.getElementById('mobileMenu').hidden=true;}}); }
document.addEventListener('DOMContentLoaded',init);
